[th2-1984] Added information about message timestamp into checkpoint
th2-net/th2-grpc-common pull request #22
Opened 2021-06-17 17:24 UTC by Nikita-Smirnov-Exactpro

2021-06-17 17:53 UTC, OptimumOpium requested changes

2021-06-17 17:53 UTC, OptimumOpium commented on src/main/proto/th2_grpc_common/common.proto
> +    * This field will be removed in future major releases.
I think we still will need to use this map until we remove it completely. So, we cannot say that check1 will not consider that field at all. In check1 we will need to check if one of the fields is set and convert the old one if the old one was used. But if both fields are set we should report an error

2021-06-18 06:51 UTC, jean-michel-perli-sonsin requested changes
Hello, please see if you agree with the changes proposed below:
README.md
Line 6 - ## How to maintain **a** project:

Line 8 - **Update the** version of Java package in `gradle.properties` file.

Line 9 - **Update the** version of Python package in `package_info.json` file.

Line 13 - If you wish to manually create and publish **a** package for Java, run these **commands**:

Line 22 - If you wish to manually create and publish **a** package for Python:

src/main/proto/th2_grpc_common/common.proto 
Line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

Line 27 - Session identifier depends on **the** protocol, target / sender

Line 76 - It **can be** used to store **an** event related to **the** message life cycle

Line 82 - It **can be** used to store **an** event related to **the** message life cycle

Line 220/230 - Event id of **a** parent event. It is **set to** null for root event

Line 232/242 - **Optional events related to each other**. No events outside **of** this batch should refer to the events in this batch

In case of any questions, please let me know.
Thanks!

2021-08-06 10:56 UTC, jean-michel-perli-sonsin commented on README.md
> +   You can find the generated files by following path: `src/gen/main/services/python`
```suggestion
   You can find the generated files in the following path: `src/gen/main/services/python`
```

2021-08-06 11:04 UTC, jean-michel-perli-sonsin commented on src/main/proto/th2_grpc_common/common.proto
> +    * It should contain one of these two fields - direction_to_sequence or direction_to_checkpoint_data, preferable to the second.
```suggestion
    * It should contain one of these two fields - direction_to_sequence or direction_to_checkpoint_data, preferably the second one.
```

2021-08-06 11:05 UTC, jean-michel-perli-sonsin commented on src/main/proto/th2_grpc_common/common.proto
> +    * This filed will be removed in future major releases. Please use direction_to_checkpoint_data instead.
```suggestion
    * This field will be removed in future major releases. Please use direction_to_checkpoint_data instead.
```

2021-08-06 11:07 UTC, jean-michel-perli-sonsin requested changes
Hello, please see if you agree with my previous comments and with the small changes proposed below:
- requirements.txt
line 1: Copyright 2020-"2021" Exactpro (Exactpro Systems Limited)

- setup.py
line 1: Copyright 2020-"2021" Exactpro (Exactpro Systems Limited)

The rest of the text/changes are ok.
Please let me know in case of any question.
Thanks!

2021-08-06 11:26 UTC, OptimumOpium requested changes
I think it is a wrong branch to merge

2021-08-06 11:26 UTC, OptimumOpium commented on .github/workflows/java-publish-sonatype.yml
> +  workflow_dispatch:
Is it okay to have the empty `workflow_dispatch` key?

2021-08-06 11:26 UTC, OptimumOpium commented on gradle.properties
> +release_version=3.3.0
Wrong version (or wrong branch)

2021-08-06 15:35 UTC, jean-michel-perli-sonsin approved these changes
All changes were performed according to the previous comments.

2021-08-06 15:38 UTC, OptimumOpium commented on src/main/proto/th2_grpc_common/common.proto
> +    map<int32, CheckpointData> direction_to_checkpoint_data = 2;
I believe we can use `oneof` here to prevent setting both `direction_to_sequence` and `direction_to_checkpoint_data`

2021-08-09 09:49 UTC, OptimumOpium requested changes

2021-08-09 09:49 UTC, OptimumOpium commented on src/main/proto/th2_grpc_common/common.proto
> +    }
We cannot apply those changes because they break backward compatibilities. We must leave the direction_to_sequence as it was

2021-08-09 10:46 UTC, OptimumOpium approved these changes

2021-08-09 10:49 UTC, merged