[TH2-1598] Add IN, LIKE, MORE, LESS filter operation
th2-net/th2-grpc-common pull request #26
Opened 2021-08-09 13:43 UTC by Sergey-Sitnikov-Exactpro

2021-08-09 17:29 UTC, OptimumOpium requested changes

2021-08-09 17:29 UTC, OptimumOpium commented on src/main/proto/th2_grpc_common/common.proto
> +  LESS = 7;
Please, add negative versions of those operations

2021-08-09 17:29 UTC, OptimumOpium commented on src/main/proto/th2_grpc_common/common.proto
> +    ComplexFilter  complex_filter= 6;
I think we should call it SimpleList or something like that. It sounds more correctly in my oppinion

2021-08-17 14:40 UTC, Sergey-Sitnikov-Exactpro commented on README.md
> ++ Added `MORE`, `LESS`, 'NOT_MORE', 'NOT_LESS' filter operations, which filter a field by comparing values
Should I specify types like java class name (e.g. LocalDate) or 
Added `MORE`, `LESS`, `NOT_MORE`, `NOT_LESS` filter operations, which filter a field by comparing values(`numeric` types and `date/time` in ISO format) is enough?

2021-08-17 16:23 UTC, OptimumOpium commented on README.md
> ++ Added `MORE`, `LESS`, 'NOT_MORE', 'NOT_LESS' filter operations, which filter a field by comparing values
I guess the second option is the best one

2021-08-18 08:48 UTC, OptimumOpium approved these changes

2021-08-18 11:42 UTC, merged